.TH OSHFORT 1 "OpenSHMEM Library Documentation"
.SH NAME
oshfort - Compiles and links OpenSHMEM programs written in Fortran
.SH DESCRIPTION
This command can be used to compile and link OpenSHMEM programs written in Fortran.
It provides the options and any special libraries that are needed to compile and link OpenSHMEM programs.

It is important to use this command, particularly when linking programs, as it provides the necessary libraries.

usage: oshfort [oshfort_options] [compiler_arguments]
.SH COMMAND LINE ARGUMENTS
.TP 8
.B --help
- Display this information
.TP
.B -showme | -show
- Print the command that would be run without executing it
.TP
.B -E | -M
- Disable compilation and linking
.TP
.B -S
- Disable linking
.TP
.B -c
- Compile and assemble. Disable link

