.TH OSHRUN 1 "OpenSHMEM Library Documentation"
.SH NAME
oshrun - Run a OpenSHMEM program
.SH DESCRIPTION
.B oshrun
launches the OpenSHMEM programs with a given number of processes.

usage: ushrun [oshrun_options] [launcher_arguments]
.SH COMMAND LINE ARGUMENTS
.TP 8
.B --help | -h
- Display this information
