.TH SHMEM_TEAM_N_PES 3 "Open Source Software Solutions, Inc." "OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
shmem_team_n_pes \- 
Returns the number of PEs in a specified team.

./ sectionEnd


./ sectionStart
.SH   SYNOPSIS
./ sectionEnd

./ sectionStart
.SS C/C++:

.B int
.B shmem\_team\_n\_pes(shmem_team_t
.I team
.B );



./ sectionEnd




./ sectionStart

.SH DESCRIPTION
.SS Arguments
.BR "IN " -
.I team
- An OpenSHMEM team handle.
./ sectionEnd


./ sectionStart

.SS API Description

When 
.I team
specifies a valid team, the
.B shmem\_team\_n\_pes
routine returns the number of PEs in
the team.
This will always be a value between 1 and N, where N is the
total number of PEs running in the OpenSHMEM program.

If 
.I team
compares equal to SHMEM\_TEAM\_INVALID,
then the value -1 is returned.
If 
.I team
is otherwise invalid, the behavior is undefined.

./ sectionEnd


./ sectionStart

.SS Return Values

The number of PEs in the specified team, or the value
-1 if the team handle compares equal to
SHMEM\_TEAM\_INVALID.

./ sectionEnd


./ sectionStart

.SS API Notes

For the world team, this routine will return the same value as
.BR "shmem\_n\_pes" .

./ sectionEnd




