.TH SHMEM_SYNC_ALL 3 "Open Source Software Solutions, Inc." "OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
shmem_sync_all \- 
Registers the arrival of a PE at a synchronization point and suspends
execution until all other PEs in the world team arrive at the synchronization point.
For multithreaded programs, execution is suspended
as specified by the OpenSHMEM threading model.
./ sectionEnd
./ sectionStart
.SH   SYNOPSIS
./ sectionEnd
./ sectionStart
.SS C/C++:
.B void
.B shmem\_sync\_all(void)
./ sectionEnd
./ sectionStart
.SH DESCRIPTION
.SS Arguments
.B None.
./ sectionEnd
./ sectionStart
.SS API Description
This routine blocks the calling PE until all PEs in the
world team have called 
.BR "shmem\_sync\_all" .
In a multithreaded OpenSHMEM program, only the calling thread is
blocked.
In contrast with the 
.B shmem\_barrier\_all
routine,
.B shmem\_sync\_all
only ensures completion and visibility of previously issued memory
stores and does not ensure completion of remote memory updates issued via
OpenSHMEM routines.
./ sectionEnd
./ sectionStart
.SS Return Values
None.
./ sectionEnd
./ sectionStart
.SS API Notes
The 
.B shmem\_sync\_all
routine is equivalent to calling
.B shmem\_team\_sync
on the world team.
./ sectionEnd
