.TH SHMEM_ATOMIC_SET 3 "Open Source Software Solutions, Inc.""OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
shmem_atomic_set \- 
Atomically sets the value of a remote data object.
./ sectionEnd
./ sectionStart
.SH   SYNOPSIS
./ sectionEnd
./ sectionStart
.SS C11:
.B void
.B shmem_atomic_set(TYPE
.IB "*dest" ,
.B TYPE
.IB "value" ,
.B int
.I pe
.B );
./ sectionEnd
where TYPE is one of the extended AMO types specified by
Table 3.
./ sectionStart
.SS C/C++:
.B void
.B shmem_<TYPENAME>_atomic_set(TYPE
.IB "*dest" ,
.B TYPE
.IB "value" ,
.B int
.I pe
.B );
./ sectionEnd
where TYPE is one of the extended AMO types and has a corresponding
TYPENAME specified by Table 3.
./ sectionStart
.SS Fortran:
.nf
.BR "INTEGER " "pe"
.BR "INTEGER*4 " "SHMEM_INT4_SET, value_i4"
.BR "CALL " "SHMEM_INT4_SET(dest, value_i4, pe)"
.BR "INTEGER*8 " "SHMEM_INT8_SET, value_i8"
.BR "CALL " "SHMEM_INT8_SET(dest, value_i8, pe)"
.BR "REAL*4 " "SHMEM_REAL4_SET, value_r4"
.BR "CALL " "SHMEM_REAL4_SET(dest, value_r4, pe)"
.BR "REAL*8 " "SHMEM_REAL8_SET, value_r8"
.BR "CALL " "SHMEM_REAL8_SET(dest, value_r8, pe)"
.fi
./ sectionEnd
./ sectionStart
.SH DESCRIPTION
.SS Arguments
.BR "IN " -
.I dest
- The remotely accessible data object to be set on
the remote PE.
.BR "IN " -
.I value
- The value to be atomically written to the remote PE.
.BR "IN " -
.I pe
- An integer that indicates the PE number on which
.I dest
is to be updated.
./ sectionEnd
./ sectionStart
.SS API Description
.B shmem\_atomic\_set
performs an atomic set operation. It writes the
.I value
into 
.I dest
on 
.I pe
as an atomic operation.
./ sectionEnd
./ sectionStart
.SS Return Values
None.
./ sectionEnd
./ sectionStart
.SS API Notes
As of OpenSHMEM[1.4], 
.B shmem\_set
has been deprecated.
Its behavior and call signature are identical to the replacement
interface, 
.BR "shmem\_atomic\_set" .
./ sectionEnd
.SS Table 3:
Extended AMO Types and Names
.TP 25
.B \TYPE
.B \TYPENAME
.TP
float
float
.TP
double
double
.TP
int
int
.TP
long
long
.TP
long long
longlong
