.TH SHMEM_CACHE 3 "Open Source Software Solutions, Inc.""OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
shmem_cache \- 
Controls data cache utilities.
./ sectionEnd
./ sectionStart
.SH   SYNOPSIS
./ sectionEnd
./ sectionStart
.B ***********DEPRECATED***********
./ sectionEnd
./ sectionStart
.SS C/C++:
.B void
.B shmem_clear_cache_inv(void)
.B void
.B shmem_set_cache_inv(void)
.B void
.B shmem_clear_cache_line_inv(void
.I *dest
.B );
.B void
.B shmem_set_cache_line_inv(void
.I *dest
.B );
.B void
.B shmem_udcflush(void)
.B void
.B shmem_udcflush_line(void
.I *dest
.B );
./ sectionEnd
./ sectionStart
.B ********************************
./ sectionEnd
./ sectionStart
.B ***********DEPRECATED***********
./ sectionEnd
./ sectionStart
.SS Fortran:
.nf
.BR "CALL " "SHMEM_CLEAR_CACHE_INV"
.BR "CALL " "SHMEM_SET_CACHE_INV"
.BR "CALL " "SHMEM_SET_CACHE_LINE_INV(dest)"
.BR "CALL " "SHMEM_UDCFLUSH"
.BR "CALL " "SHMEM_UDCFLUSH_LINE(dest)"
.fi
./ sectionEnd
./ sectionStart
.B ********************************
./ sectionEnd
./ sectionStart
.SH DESCRIPTION
.SS Arguments
.BR "IN " -
.I dest
- A data object that is local to the PE. 
.I dest
can be of any noncharacter type. If you are using Fortran, it can be of any
kind.
./ sectionEnd
./ sectionStart
.SS API Description
.B shmem\_set\_cache\_inv
enables automatic cache coherency mode.
.B shmem\_set\_cache\_line\_inv
enables automatic cache coherency mode for
the cache line associated with the address of 
.I dest
only.
.B shmem\_clear\_cache\_inv
disables automatic cache coherency mode
previously enabled by 
.B shmem\_set\_cache\ \_inv
or
.BR "shmem\_set\_cache\_line\_inv" .
.B shmem\_udcflush
makes the entire user data cache coherent.
.B shmem\_udcflush\_line
makes coherent the cache line that corresponds with
the address specified by 
.IR "dest" .
.
./ sectionEnd
./ sectionStart
.SS Return Values
None.
./ sectionEnd
./ sectionStart
.SS API Notes
These routines have been retained for improved backward compatibility with
legacy architectures. They are not required to be supported by implementing
them as 
.I no-ops
and where used, they may have no effect on cache line
states.
./ sectionEnd
./ sectionStart
.SS Examples
None.
