.TH SHPDEALLC 3 "Open Source Software Solutions, Inc." "OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
shpdeallc \- 
Returns a memory block to the symmetric heap.

./ sectionEnd


./ sectionStart
.SH   SYNOPSIS
./ sectionEnd

./ sectionStart

.B ***************DEPRECATED***************
.SS Fortran:

.nf

.BR "POINTER " "(addr, A(1))"
.BR "INTEGER " "errcode, abort"
.BR "CALL " "SHPDEALLC(addr, errcode, abort)"

.fi
.B ****************************************

./ sectionEnd




./ sectionStart

.SH DESCRIPTION
.SS Arguments
.BR "IN " -
.I addr
-  First word address of the block to deallocate.


.BR "OUT " -
.I errcode
- Error code is 0 if no error was detected;
otherwise, it is a negative integer code for the type of error.


.BR "IN " -
.I abort
- Abort code. Nonzero requests abort on error;
0 requests an error code.
./ sectionEnd


./ sectionStart

.SS API Description

SHPDEALLC returns a block of memory (allocated using 
.B SHPALLOC
) to the
list of available space in the symmetric heap. To maintain symmetric heap
consistency, all PEs in a program must call 
.B SHPDEALLC
with the same
value of 
.I addr
; if any PEs are missing, the program hangs.

./ sectionEnd


./ sectionStart

.SS Return Values

./ sectionEnd


./ sectionStart
.TP 25
Error Code
Condition
./ sectionEnd


./ sectionStart
.TP 25
-1 
Length is not an integer greater than 0
./ sectionEnd


./ sectionStart
.TP 25
-2
No more memory is available from the system (checked if the request cannot be satisfied from the available blocks on the symmetric heap).
./ sectionEnd


./ sectionStart
.TP 25
-3
Address is outside the bounds of the symmetric heap.
./ sectionEnd


./ sectionStart
.TP 25
-4
Block is already free.
./ sectionEnd


./ sectionStart
.TP 25
-5
Address is not at the beginning of a block.
./ sectionEnd


./ sectionStart

.SS API Notes

None.

./ sectionEnd




