.TH START_PES 3 "Open Source Software Solutions, Inc." "OpenSHMEM Library Documentation"
./ sectionStart
.SH NAME
start_pes \- 
Called at the beginning of an OpenSHMEM program to initialize the execution
environment. This routine is deprecated and is provided for backwards
compatibility. Implementations must include it, and the routine should
function properly and may notify the user about deprecation of its use.

./ sectionEnd


./ sectionStart
.SH   SYNOPSIS
./ sectionEnd



./ sectionStart
.B ***************DEPRECATED***************
./ sectionEnd

./ sectionStart
.SS C/C++:

.B void
.B start\_pes(int
.I npes
.B );



./ sectionEnd



./ sectionStart
.B ****************************************
./ sectionEnd

./ sectionStart

.SH DESCRIPTION
.SS Arguments
.BR "npes " -
.I Unused
-  Should be set to 0.
./ sectionEnd


./ sectionStart

.SS API Description

The 
.B start\_pes
routine initializes the OpenSHMEM execution
environment. An OpenSHMEM program must call 
.BR "start\_pes" ,
.BR "shmem\_init" ,
or 
.B shmem\_init\_thread
before calling any other OpenSHMEM routine. Unlike
.B shmem\_init
and 
.BR "shmem\_init\_thread" ,
.B start\_pes
does not require a call to
.BR "shmem\_finalize" .
Instead, the OpenSHMEM library is implicitly
finalized when the program exits. Implicit finalization is collective and
includes a global synchronization to ensure that all pending communication
is completed before resources are released.

./ sectionEnd


./ sectionStart

.SS Return Values

None.

./ sectionEnd


./ sectionStart

.SS API Notes

If any other OpenSHMEM call occurs before 
.BR "start\_pes" ,
the
behavior is undefined. Although it is recommended to set 
.I npes
to
0 for 
.BR "start\_pes" ,
this is not mandated. The value is ignored.
Calling 
.B start\_pes
more than once has no subsequent
effect.

As of OpenSHMEM[1.2] the use of 
.B start\_pes
has
been deprecated. Although OpenSHMEM libraries are required to support the
call, users are encouraged to use 
.B shmem\_init
or
.B shmem\_init\_thread
instead.

./ sectionEnd




