define(`SHMEM_BIND_C11_RMA_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_EXTENDED_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_BITWISE_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_SYNC_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_COLL_AND_OR_XOR_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_COLL_MIN_MAX_EXTRAS', `')dnl
define(`SHMEM_BIND_C11_COLL_SUM_PROD_EXTRAS', `')dnl
