define(`SHMEM_BIND_CXX_RMA_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_EXTENDED_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_BITWISE_AMO_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_SYNC_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_COLL_AND_OR_XOR_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_COLL_MIN_MAX_EXTRAS', `')dnl
define(`SHMEM_BIND_CXX_COLL_SUM_PROD_EXTRAS', `')dnl
